# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('episode', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('scan_type', models.CharField(max_length=200)),
                ('attachement', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
            ],
        ),
    ]
